name: Test kickstart.sh

on:
  push:
    branches: [main]
  pull_request:

jobs:
  rpm-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - fedora:42
          - fedora:41
          - fedora:40
          - amazonlinux:latest
          - rockylinux:latest
    container: ${{ matrix.container }}
    steps:
      - name: Install basic tools
        run: |
          if command -v dnf; then
            dnf update -y
          elif command -v yum; then
            yum update -y
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run kickstart.sh
        run: |
          chmod +x kickstart.sh
          ./kickstart.sh
