name: Test kickstart.sh

on:
  push:
    branches: [main]
  pull_request:

jobs:
  rpm-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - fedora:42
          - fedora:40
          - amazonlinux:latest
          - amazonlinux:2
          - rockylinux:9
          - rockylinux:8
          - ubi9/ubi
          - ubi10/ubi
    container: ${{ matrix.container }}
    steps:
      - name: Install basic tools
        run: |
          if command -v dnf; then
            dnf install tar gzip -y && dnf info nano
          elif command -v yum; then
            yum install tar gzip -y && dnf info nano
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run kickstart.sh
        run: |
          chmod +x kickstart.sh
          ./kickstart.sh
