name: Test kickstart.sh

on:
  push:
    branches: [main]
  pull_request:

jobs:
  rpm-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - fedora:42
          - fedora:40
          - amazonlinux:latest
          - amazonlinux:2
          - rockylinux:9
          - rockylinux:8
    container: ${{ matrix.container }}
    steps:
      - name: Install basic tools
        run: |
          if command -v dnf; then
            dnf update -y && dnf install tar gzip git -y && dnf info nano
          elif command -v yum; then
            yum update -y && yum install tar gzip git -y && yum info nano
          fi

      - name: Fetch Repo & Run Kickstart.sh
        run: |
          git clone https://github.com/ArthurMacTavish/CICD-Testbed && ls && cd CICD-Testbed
          chmod +x kickstart.sh
          ./kickstart.sh
